Patches to fix sIRC bugs and enhancements
Channel: equals() checks for IrcConnection equality; add hashCode()

IrcConnection: make ABOUT non-final, make GC false (unnecessary for any VM
in the past 10 years). Interrupt I/O threads when disconnecting.  Support
a custom SSLContext for connecting to SSL. Support renegotiating an in-use
nick. Support reply 464: password incorrect. Make setConnected public (so
third-party apps can forcefully disconnect).  Add setUsername()

IrcDecoder: support username in User

IrcInput: name the thread with the remote host and username

IrcOutput: name the thread with remote host and username; do not swallow
exceptions silently in sendNow() [caused a PITA bug on android 3.0+ StrictMode]

IrcParser: fix onJoin channel vs. line.getMessage()

User: add realname field

PasswordException: new exception to support reply 464